---
- hosts:
    - localhost
  roles:
    - roles/ansible-role-rhel-vanilla
    - roles/ansible-role-rhel-local-hardening-tasks
    - roles/rhel8STIG-ansible-lockdown
  serial: 50
  become: yes
  vars:
    rhel8stig_bootloader_password_hash: "changethispassword"
    rhel8stig_010380: false # RHEL 8 must require users to provide a password for privilege escalation.
